Mover archivos de datos a su propio directorio
GeoLatinas/Intro-to-python pull request #11
Opened 2021-02-11 20:31 UTC by MGomezN

Crear folder con archivos .csv, .dat, .txt  usados en los notebook

2021-02-11 21:58 UTC, MGomezN commented
@santisoler  Podría por favor verificar mis modificaciones? En realidad sólo hice cambios a los notebooks 4 y al 8... no entendí por qué se mandaron tantas cosas más jaja (lo de las versiones).

2021-02-11 22:15 UTC, santisoler commented
Está muy bien lo que hiciste @MGomezN!

Si bien hiciste cambios en las celdas de los notebooks 4 y 8,  en algún momento abriste los otros y los guardaste.
A pesar de que no hayas modificado ninguna de celdas de esos otros, Jupyter al guardar sobreescribe cierta metadata (como la versión de Python que estás usando, etc). Eso es en sí un cambio en el archivo `.ipynb` que git registra.

Una opción para evitar eso es seleccionar qué archivo queremos agregar al commit con:
```
git add <nombre-de-archivo>
```
en vez de agregar todo el working directory con:
```
git add .
```

Pero no te preocupes, yo diría de mergear este PR así como está. No pasa nada con esos cambios en los otros notebooks.

2021-02-11 22:19 UTC, santisoler requested changes
Está muy bien lo que hiciste @MGomezN! 🥇 :tada:

Si bien hiciste cambios en las celdas de los notebooks 4 y 8,  en algún momento abriste los otros y los guardaste.
A pesar de que no hayas modificado ninguna de celdas de esos otros, Jupyter al guardar sobreescribe cierta metadata (como la versión de Python que estás usando, etc). Eso es en sí un cambio en el archivo `.ipynb` que git registra.

Una opción para evitar eso es seleccionar qué archivo queremos agregar al commit con:
```
git add <nombre-de-archivo>
```
en vez de agregar todo el working directory con:
```
git add .
```

Pero no te preocupes, por los cambios en esos notebooks, los podemos mergear sin problema.

Lo que sí haría antes de mergear es sacar el archivo que bajó Numpy, el de temperatura:
`notebooks/berkeleyearth.lbl.gov/auto/Global/Land_and_Ocean_summary.txt `

Eso lo podés hacer con:
```
git rm notebooks/berkeleyearth.lbl.gov/auto/Global/Land_and_Ocean_summary.txt 
```
Hacés el commit y después pusheas.

2021-02-12 06:03 UTC, MGomezN commented
@santisoler  Qué tal? Cómo me fue esta vez? Gracias por la paciencia! Otra duda. Veo que a veces escribimos en español, otras en Inglés debería ser uniforme verdad? Siempre en inglés? O no pasa nada?

2021-02-12 12:38 UTC, santisoler commented
> @santisoler Qué tal? Cómo me fue esta vez? Gracias por la paciencia! 

No hay problema!

Veo que no sacaste el archivo de temperaturas de Berkely, sino que lo agregaste al repositorio y modificaste el notebook en el cual lo usamos para que lo leyera directamente desde el disco en vez de que lo descargue de la web.
Justo ese archivo yo dejaría que lo descarguen de la web, para que vean cómo pueden trabajar con archivos "reales" sin que nosotros le brindemos archivos de datos ya limpios. De hecho, algo curioso que pasó con esé archivo es que es distinto al que usé para mi curso: agregaron los datos de 2020!

Entonces mi propuesta sería:
- eliminar el `Land_and_Ocean_summary.txt`
- dejar que el notebook lo baje desde la url con numpy (como lo hacía antes)

Si tenés alguna duda, podemos charlar y solucionarla.

> Otra duda. Veo que a veces escribimos en español, otras en Inglés debería ser uniforme verdad? Siempre en inglés? O no pasa nada?

Me contagio de @isamarcortes a veces jaja. Como el curso lo vamos a dar en español, yo diría que toda explicación, narrativa, etc la hagamos en español. Creo que con los nombres de las variables podemos ser más flexibles, por ejemplo no me parece mal usar `years` o `temperature`. Y con respecto a los commits messages y los PRs, ahí podemos hacer lo que queramos y sacar nuestro mejor spanglish a relucir jaja.

2021-02-12 13:42 UTC, MGomezN commented
@santisoler  jaja yo entendí "sacar" como evitar que bajaran el archivo de Internet...Totalmente al revés!
Pero esto me ayuda a buscar cómo hacer para que pueda regresar en mi repositorio local a la versión original del notebook 7 y restaurarla, pues no había nada que hacerle al notebook...

2021-02-12 13:58 UTC, santisoler commented
Jaja, perdón si no fui muy claro!

Podés revertir commits con `git revert`. Para eso primero tenés que ejecutar `git log` y buscar el hash del commit que queres revertir (la cadena de caracteres larga que aparece al ppio de cada commit, es un número hexadecimal que identifica al commit). Después podés hacer un revert:
```
git revert <hash-del-commit>
```

Esto lo que hace es crear un nuevo commit que revierte los cambios del commit que pasaste como argumento.

2021-02-12 23:13 UTC, MGomezN commented
@santisoler  podría por favor verificar si ya quedó? Me di cuenta que data estaba dentro de notebooks, entonces la moví y actualicé el path...

2021-02-17 21:04 UTC, santisoler approved these changes

2021-02-17 21:05 UTC, santisoler commented
Muy bueno @MGomezN ! 🏅  Creo que está listo para mergear. Así que si querés podés hacer un Squash and merge.

2021-02-17 22:29 UTC, merged

2021-02-17 22:31 UTC, MGomezN commented
@santisoler  ¡qué felicidad! por fin dice "successfully" ... agarrate Boule! ya no te tengo miedo :P